# Generated by Django 3.0.6 on 2020-05-16 12:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SmartContract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('account_no', models.CharField(max_length=200)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('submission_period_days', models.IntegerField(blank=True, null=True)),
                ('submission_period_hours', models.IntegerField(blank=True, null=True)),
                ('submission_period_minutes', models.IntegerField(blank=True, null=True)),
                ('contract_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
                ('contract_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ml_exchange.SmartContract')),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
                ('contract_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ml_exchange.SmartContract')),
            ],
        ),
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
                ('contract_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ml_exchange.SmartContract')),
            ],
        ),
    ]
