# Generated by Django 3.0.6 on 2020-05-18 12:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ml_exchange', '0004_auto_20200518_1142'),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('training_data', models.FileField(upload_to='')),
                ('testing_data', models.FileField(upload_to='')),
                ('accuracy', models.FloatField(blank=True, null=True)),
                ('viewed_training_data', models.BooleanField(default=False)),
                ('model', models.FileField(blank=True, null=True, upload_to='')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ml_exchange.SmartContract')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Model',
        ),
    ]
