# Generated by Django 3.0.6 on 2020-05-21 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml_exchange', '0005_auto_20200518_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='testing_data',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='submission',
            name='training_data',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
