# Generated by Django 3.0.6 on 2020-05-24 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml_exchange', '0007_auto_20200524_0751'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='request',
            name='dataset',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
