# Generated by Django 3.0.6 on 2020-05-24 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ml_exchange', '0008_auto_20200524_1342'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='contract',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ml_exchange.SmartContract'),
        ),
    ]
