# Generated by Django 3.0.6 on 2020-05-24 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml_exchange', '0009_request_contract'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='viewed',
            field=models.BooleanField(default=False),
        ),
    ]
