# Generated by Django 3.0.6 on 2020-05-24 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml_exchange', '0010_request_viewed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='contract_no',
        ),
        migrations.AddField(
            model_name='smartcontract',
            name='dataset',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='smartcontract',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.DeleteModel(
            name='Dataset',
        ),
        migrations.DeleteModel(
            name='Document',
        ),
    ]
