# Generated by Django 3.0.6 on 2020-05-24 14:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ml_exchange', '0011_auto_20200524_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='smartcontract',
            name='best_submission_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='best_submission', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='smartcontract',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creator', to=settings.AUTH_USER_MODEL),
        ),
    ]
