# Generated by Django 3.0.6 on 2020-05-24 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml_exchange', '0012_auto_20200524_1456'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
