# Generated by Django 3.0.6 on 2020-06-18 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml_exchange', '0013_request_document'),
    ]

    operations = [
        migrations.CreateModel(
            name='run_init',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('done', models.BooleanField(default=False)),
            ],
        ),
    ]
