# Generated by Django 3.0.6 on 2020-06-20 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml_exchange', '0018_submission_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='ether',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
